version: '3'
services:
    server:
        build: 
            context: ./server
        depends_on: 
            - db
        links:
            - db
        ports:
            - "8080:80"
    client_web:
        build: 
            context: ./client_web
        ports:
            - "8081:4200"
        links:
            - server
        volumes:
            - ".:/src/assets"
    mobile_user:
        build:
            context: ./mobile_user
        volumes:
            - ".:/app/app/build/outputs/apk/release"
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"